version: "3.7"
services:

  php-fpm:
    container_name: ${COMPOSE_PROJECT_NAME}-php-fpm
    build:
      context: php-fpm
      args:
        - PHP_VERSION=${PHP_VERSION}
        - COMPOSER_VERSION=${COMPOSER_VERSION}
    expose:
      - "9000"
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    working_dir: ${APP_CODE_PATH_CONTAINER}
    networks:
      - hotelier

  nginx:
    image: nginx:1.18-alpine
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    restart: unless-stopped
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
    volumes:
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - hotelier


networks:
  hotelier:
    driver: ${NETWORKS_DRIVER}